services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    env_file: 
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
    user: "1000:1000"
